services:
  - type: web
    name: coreiq-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
