import { StyleSheet } from 'react-native';

export function createDashboardStyles(isLight: boolean) {
  const palette = {
    bg: isLight ? '#ffffff' : '#181818',
    bg2: isLight ? '#f2f4f7' : '#1f1f1f',
    text: isLight ? '#111' : '#fff',
    textMuted: isLight ? '#475467' : '#aaa',
    border: isLight ? '#e5e7eb' : '#333',
    border2: isLight ? '#e5e7eb' : '#222',
    navBg: isLight ? '#ffffff' : '#181818',
    inputBg: isLight ? '#f8fafc' : '#2a2a2a',
    overlay: 'rgba(0, 0, 0, 0.5)'
  };
  return StyleSheet.create({
    container: { flex: 1 },
    scrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 100,
    },
    header: {
      backgroundColor: palette.bg,
      flexDirection: 'column',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: palette.border2,
    },
    welcome: {
      color: palette.textMuted,
      fontSize: 16,
    },
    userName: {
      fontWeight: 'bold',
      color: '#2563eb',
    },
    avatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#fff',
    },
    sectionHeader: {
      color: palette.text,
      fontSize: 18,
      fontWeight: '600',
      paddingTop: 50,
      marginBottom: 12,
    },
    cardGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 16,
    },
    card: {
      width: '47%',
      backgroundColor: palette.bg2,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
    cardTitle: {
      color: palette.textMuted,
      fontSize: 14,
      marginTop: 8,
    },
    cardValue: {
      color: palette.text,
      fontSize: 20,
      fontWeight: '600',
      marginTop: 4,
    },
    navbar: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      backgroundColor: palette.navBg,
      paddingVertical: 8,
      paddingBottom: 35,
      borderTopWidth: 1,
      borderTopColor: palette.border2,
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 100,
    },
    navItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 2,
    },
    navLabel: {
      color: isLight ? '#667085' : '#888',
      fontSize: 12,
      marginTop: 2,
      fontWeight: '500',
    },
    navLabelActive: {
      color: '#2563eb',
      fontWeight: '700',
    },
    dateBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.bg,
      paddingVertical: 0,
      alignSelf: 'center',
      marginTop: 8,
      marginBottom: 0,
    },
    dateText: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '500',
      marginHorizontal: 16,
      paddingVertical: 4,
    },
    headerTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    profileButton: {
      padding: 4,
    },
    // Modals
    modalOverlay: {
      flex: 1,
      backgroundColor: palette.overlay,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      backgroundColor: palette.bg2,
      borderRadius: 16,
      padding: 24,
      width: '90%',
      maxHeight: '90%',
      minHeight: 400,
      borderWidth: 1,
      borderColor: palette.border,
    },
    modalTitle: {
      color: palette.text,
      fontSize: 20,
      fontWeight: '600',
      textAlign: 'center',
      marginBottom: 8,
    },
    modalSubtitle: {
      color: palette.textMuted,
      fontSize: 14,
      textAlign: 'center',
      marginBottom: 20,
    },
    waterInput: {
      backgroundColor: palette.inputBg,
      borderRadius: 8,
      padding: 16,
      color: palette.text,
      fontSize: 16,
      marginBottom: 16,
      textAlign: 'center',
      position: 'relative',
      borderWidth: 1,
      borderColor: palette.border,
    },
    clearButton: {
      position: 'absolute',
      right: 16,
      top: 16,
      zIndex: 1,
    },
    quickButtons: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 24,
    },
    quickButton: {
      backgroundColor: palette.inputBg,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: palette.border,
    },
    quickButtonText: {
      color: '#2563eb',
      fontSize: 14,
      fontWeight: '500',
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    modalButton: {
      flex: 1,
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      minHeight: 50,
    },
    inlineButton: {
      flex: 0,
      alignSelf: 'center',
      minWidth: 140,
      paddingVertical: 10,
      paddingHorizontal: 16,
      minHeight: 42,
      marginTop: 10,
    },
    fullWidthButton: {
      flex: 0,
      alignSelf: 'stretch',
      width: '100%',
      paddingVertical: 14,
      minHeight: 50,
      marginTop: 10,
    },
    cancelButton: {
      backgroundColor: palette.inputBg,
      borderWidth: 1,
      borderColor: palette.border,
    },
    confirmButton: {
      backgroundColor: '#2563eb',
    },
    compactButton: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      minHeight: 42,
      marginTop: 6,
    },
    cancelButtonText: {
      color: palette.textMuted,
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
      includeFontPadding: false,
    },
    confirmButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
      includeFontPadding: false,
    },
    compactButtonText: {
      fontSize: 15,
    },
    mentalOptionsContainer: {
      maxHeight: 300,
      marginBottom: 20,
    },
    mentalOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginBottom: 8,
      backgroundColor: palette.inputBg,
      borderWidth: 1,
      borderColor: palette.border,
    },
    selectedMentalOption: {
      backgroundColor: '#1e40af',
    },
    mentalOptionText: {
      color: palette.text,
      fontSize: 16,
      marginLeft: 12,
      fontWeight: '500',
    },
    selectedMentalOptionText: {
      color: '#fff',
      fontWeight: '600',
    },
    currentWaterDisplay: {
      backgroundColor: palette.inputBg,
      padding: 12,
      borderRadius: 8,
      marginBottom: 16,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.border,
    },
    currentWaterText: {
      color: '#2563eb',
      fontSize: 16,
      fontWeight: '600',
    },
    resetButton: {
      backgroundColor: '#dc2626',
    },
    resetButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '500',
    },
    subtractButton: {
      backgroundColor: '#dc2626',
    },
    subtractButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '500',
    },
    categoryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginTop: 24,
      marginBottom: 24,
      gap: 16,
      paddingHorizontal: 4,
    },
    categoryCard: {
      width: '47%',
      backgroundColor: palette.bg2,
      borderRadius: 20,
      alignItems: 'center',
      paddingVertical: 32,
      paddingHorizontal: 16,
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      borderWidth: 1,
      borderColor: palette.border,
    },
    categoryTitle: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '700',
      marginTop: 12,
      textAlign: 'center',
    },
    categorySummary: {
      color: palette.textMuted,
      fontSize: 12,
      marginTop: 6,
      textAlign: 'center',
      lineHeight: 16,
    },
    sheetOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.3)',
      justifyContent: 'flex-end',
    },
    sheetOverlayTouch: {
      flex: 1,
    },
    bottomSheet: {
      backgroundColor: palette.bg,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 20,
      height: 500,
      elevation: 10,
    },
    sheetHandle: {
      width: 48,
      height: 6,
      borderRadius: 3,
      backgroundColor: isLight ? '#e5e7eb' : '#333',
      alignSelf: 'center',
      marginBottom: 16,
    },
    sheetContent: {
      flex: 1,
    },
    sheetScrollView: {
      flex: 1,
      paddingHorizontal: 4,
    },
    sheetTitle: {
      color: palette.text,
      fontSize: 20,
      fontWeight: '700',
      marginBottom: 16,
      textAlign: 'center',
    },
    sheetCards: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      justifyContent: 'space-between',
      paddingBottom: 20,
    },
    inputGroup: {
      marginBottom: 16,
    },
    inputLabel: {
      color: palette.textMuted,
      fontSize: 14,
      marginBottom: 8,
    },
    profileInput: {
      backgroundColor: palette.inputBg,
      borderRadius: 8,
      padding: 16,
      color: palette.text,
      fontSize: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
    profileInfo: {
      backgroundColor: palette.inputBg,
      borderRadius: 8,
      padding: 16,
      marginTop: 8,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.border,
    },
    profileInfoText: {
      color: palette.textMuted,
      fontSize: 14,
    },
    profileSection: {
      marginTop: 0,
    },
    profileCard: {
      backgroundColor: palette.bg2,
      borderRadius: 16,
      padding: 20,
      marginTop: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    profileCardContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    profileCardText: {
      flex: 1,
      marginLeft: 16,
    },
    profileCardTitle: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '600',
    },
    profileCardSubtitle: {
      color: palette.textMuted,
      fontSize: 14,
      marginTop: 2,
    },
    physicalStatsGrid: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 12,
    },
    physicalStatCard: {
      flex: 1,
      backgroundColor: palette.bg2,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
    physicalStatContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    physicalStatText: {
      flex: 1,
      marginLeft: 12,
    },
    physicalStatTitle: {
      color: palette.textMuted,
      fontSize: 14,
      marginBottom: 2,
    },
    physicalStatValue: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '600',
    },
    editButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: palette.inputBg,
      borderWidth: 1,
      borderColor: palette.border,
    },
    goalsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginTop: 12,
      gap: 12,
    },
    goalCard: {
      width: '47%',
      backgroundColor: palette.bg2,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
    goalCardContent: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    goalCardText: {
      flex: 1,
      marginLeft: 12,
    },
    goalCardTitle: {
      color: palette.textMuted,
      fontSize: 14,
      marginBottom: 2,
    },
    goalCardValue: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '600',
    },
    activityOptionText: {
      marginLeft: 12,
    },
    activityOptionDescription: {
      color: palette.textMuted,
      fontSize: 12,
      marginTop: 2,
    },
    modalHeader: {
      alignItems: 'center',
      marginBottom: 16,
    },
    currentWeightSection: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.inputBg,
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
    currentWeightText: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 10,
    },
    optionsSection: {
      marginBottom: 16,
    },
    sectionLabel: {
      color: palette.textMuted,
      fontSize: 14,
      marginBottom: 8,
    },
    goalOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginBottom: 8,
      backgroundColor: palette.inputBg,
      borderWidth: 1,
      borderColor: palette.border,
    },
    selectedGoalOption: {
      backgroundColor: '#1e40af',
    },
    goalOptionIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isLight ? '#eef2ff' : '#333',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    goalOptionContent: {
      flex: 1,
    },
    goalOptionTitle: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '500',
    },
    goalOptionDescription: {
      color: palette.textMuted,
      fontSize: 12,
      marginTop: 2,
    },
    selectedGoalOptionText: {
      color: '#fff',
    },
    targetSection: {
      marginTop: 16,
    },
    targetInput: {
      backgroundColor: palette.inputBg,
      borderRadius: 8,
      padding: 16,
      color: palette.text,
      fontSize: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
  });
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  header: {
    backgroundColor: '#181818',
    flexDirection: 'column', // Stack children vertically
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#222',
  },
  welcome: {
    color: '#ccc',
    fontSize: 16,
  },
  userName: {
    fontWeight: 'bold',
    color: '#2563eb',
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#fff',
  },
  sectionHeader: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    paddingTop: 50,
    marginBottom: 12,
  },
  cardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 16,
  },
  card: {
    width: '47%',
    backgroundColor: '#1f1f1f',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  cardTitle: {
    color: '#aaa',
    fontSize: 14,
    marginTop: 8,
  },
  cardValue: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '600',
    marginTop: 4,
  },
  navbar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#181818',
    paddingVertical: 8,
    paddingBottom: 35,
    borderTopWidth: 1,
    borderTopColor: '#222',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 2,
  },
  navLabel: {
    color: '#888',
    fontSize: 12,
    marginTop: 2,
    fontWeight: '500',
  },
  navLabelActive: {
    color: '#2563eb',
    fontWeight: '700',
  },
  dateBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#181818',
    paddingVertical: 0,
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 0,
  },
  dateText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
    marginHorizontal: 16,
    paddingVertical: 4,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileButton: {
    padding: 4,
  },
  // Add modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1f1f1f',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    maxHeight: '90%',
    minHeight: 400,
  },
  modalTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  modalSubtitle: {
    color: '#aaa',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 20,
  },
  waterInput: {
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 16,
    color: '#fff',
    fontSize: 16,
    marginBottom: 16,
    textAlign: 'center',
    position: 'relative',
  },
  clearButton: {
    position: 'absolute',
    right: 16,
    top: 16,
    zIndex: 1,
  },
  quickButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 24,
  },
  quickButton: {
    backgroundColor: '#2a2a2a',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  quickButtonText: {
    color: '#60a5fa',
    fontSize: 14,
    fontWeight: '500',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    minHeight: 50,
  },
  inlineButton: {
    flex: 0,
    alignSelf: 'center',
    minWidth: 140,
    paddingVertical: 10,
    paddingHorizontal: 16,
    minHeight: 42,
    marginTop: 10,
  },
  fullWidthButton: {
    flex: 0,
    alignSelf: 'stretch',
    width: '100%',
    paddingVertical: 14,
    minHeight: 50,
    marginTop: 10,
  },
  cancelButton: {
    backgroundColor: '#2a2a2a',
  },
  confirmButton: {
    backgroundColor: '#2563eb',
  },
  compactButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    minHeight: 42,
    marginTop: 6,
  },
  cancelButtonText: {
    color: '#aaa',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    includeFontPadding: false,
  },
  confirmButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    includeFontPadding: false,
  },
  compactButtonText: {
    fontSize: 15,
  },
  mentalOptionsContainer: {
    maxHeight: 300,
    marginBottom: 20,
  },
  mentalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#2a2a2a',
  },
  selectedMentalOption: {
    backgroundColor: '#1e40af',
  },
  mentalOptionText: {
    color: '#fff',
    fontSize: 16,
    marginLeft: 12,
    fontWeight: '500',
  },
  selectedMentalOptionText: {
    color: '#fff',
    fontWeight: '600',
  },
  currentWaterDisplay: {
    backgroundColor: '#2a2a2a',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    alignItems: 'center',
  },
  currentWaterText: {
    color: '#60a5fa',
    fontSize: 16,
    fontWeight: '600',
  },
  resetButton: {
    backgroundColor: '#dc2626',
  },
  resetButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  subtractButton: {
    backgroundColor: '#dc2626',
  },
  subtractButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 24,
    marginBottom: 24,
    gap: 16,
    paddingHorizontal: 4,
  },
  categoryCard: {
    width: '47%',
    backgroundColor: '#1f1f1f',
    borderRadius: 20,
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 16,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: '#333',
  },
  categoryTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginTop: 12,
    textAlign: 'center',
  },
  categorySummary: {
    color: '#888',
    fontSize: 12,
    marginTop: 6,
    textAlign: 'center',
    lineHeight: 16,
  },
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'flex-end',
  },
  sheetOverlayTouch: {
    flex: 1,
  },
  bottomSheet: {
    backgroundColor: '#181818',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    height: 500,
    elevation: 10,
  },
  sheetHandle: {
    width: 48,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#333',
    alignSelf: 'center',
    marginBottom: 16,
  },
  sheetContent: {
    flex: 1,
  },
  sheetScrollView: {
    flex: 1,
    paddingHorizontal: 4,
  },
  sheetTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 16,
    textAlign: 'center',
  },
  sheetCards: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
    paddingBottom: 20, // Add padding at bottom for scrolling
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    color: '#aaa',
    fontSize: 14,
    marginBottom: 8,
  },
  profileInput: {
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 16,
    color: '#fff',
    fontSize: 16,
  },
  profileInfo: {
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 16,
    marginTop: 8,
    alignItems: 'center',
  },
  profileInfoText: {
    color: '#888',
    fontSize: 14,
  },
  profileSection: {
    marginTop: 0, // Reduced from 32 to 16
  },
  profileCard: {
    backgroundColor: '#1f1f1f',
    borderRadius: 16,
    padding: 20,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  profileCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileCardText: {
    flex: 1,
    marginLeft: 16,
  },
  profileCardTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  profileCardSubtitle: {
    color: '#888',
    fontSize: 14,
    marginTop: 2,
  },
  physicalStatsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  physicalStatCard: {
    flex: 1,
    backgroundColor: '#1f1f1f',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#333',
  },
  physicalStatContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  physicalStatText: {
    flex: 1,
    marginLeft: 12,
  },
  physicalStatTitle: {
    color: '#aaa',
    fontSize: 14,
    marginBottom: 2,
  },
  physicalStatValue: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  editButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#2a2a2a',
  },
  goalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 12,
    gap: 12,
  },
  goalCard: {
    width: '47%',
    backgroundColor: '#1f1f1f',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#333',
  },
  goalCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  goalCardText: {
    flex: 1,
    marginLeft: 12,
  },
  goalCardTitle: {
    color: '#aaa',
    fontSize: 14,
    marginBottom: 2,
  },
  goalCardValue: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  activityOptionText: {
    marginLeft: 12,
  },
  activityOptionDescription: {
    color: '#888',
    fontSize: 12,
    marginTop: 2,
  },
  modalHeader: {
    alignItems: 'center',
    marginBottom: 16,
  },
  currentWeightSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  currentWeightText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 10,
  },
  optionsSection: {
    marginBottom: 16,
  },
  sectionLabel: {
    color: '#aaa',
    fontSize: 14,
    marginBottom: 8,
  },
  goalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#2a2a2a',
  },
  selectedGoalOption: {
    backgroundColor: '#1e40af',
  },
  goalOptionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  goalOptionContent: {
    flex: 1,
  },
  goalOptionTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  goalOptionDescription: {
    color: '#888',
    fontSize: 12,
    marginTop: 2,
  },
  selectedGoalOptionText: {
    color: '#fff',
  },
  targetSection: {
    marginTop: 16,
  },
  targetInput: {
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 16,
    color: '#fff',
    fontSize: 16,
    marginBottom: 16,
  },
});

export default styles; 