import { StyleSheet } from 'react-native';

export function createDashboardStyles(isLight: boolean) {
  const palette = {
    bg: isLight ? '#f8fafc' : '#000000', // PURE BLACK
    bg2: isLight ? '#ffffff' : '#121212', // Dark Grey for cards
    text: isLight ? '#0f172a' : '#ffffff',
    textMuted: isLight ? '#64748b' : '#A0A0A0', // Neutral Grey (No Blue)
    border: isLight ? 'rgba(0,0,0,0.05)' : '#333333',
    border2: isLight ? '#f1f5f9' : '#222222',
    navBg: isLight ? '#ffffff' : '#000000',
    inputBg: isLight ? '#f8fafc' : '#1A1A1A',
    primary: '#8b5cf6', // Violet
    overlay: 'rgba(0, 0, 0, 0.7)'
  };
  const styles = StyleSheet.create({
    container: { flex: 1 },
    scrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 100,
    },
    header: {
      backgroundColor: palette.bg,
      flexDirection: 'column',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: palette.border2,
    },
    welcome: {
      color: palette.textMuted,
      fontSize: 16,
      fontWeight: '500',
    },
    userName: {
      fontWeight: '800',
      color: palette.primary,
      letterSpacing: -0.5,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 14,
      backgroundColor: palette.bg2,
      borderWidth: 1,
      borderColor: palette.border,
    },
    sectionHeader: {
      color: palette.text,
      fontSize: 18,
      fontWeight: '800',
      paddingTop: 32,
      marginBottom: 16,
      letterSpacing: -0.5,
    },
    cardGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 16,
    },
    card: {
      width: '47%',
      backgroundColor: palette.bg2,
      borderRadius: 24,
      padding: 20,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: palette.border,
      shadowColor: palette.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isLight ? 0.04 : 0.2,
      shadowRadius: 12,
      elevation: 2,
    },
    cardTitle: {
      color: palette.textMuted,
      fontSize: 13,
      fontWeight: '600',
      marginTop: 8,
    },
    cardValue: {
      color: palette.text,
      fontSize: 22,
      fontWeight: '700',
      marginTop: 4,
      letterSpacing: -0.5,
    },
    navbar: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      backgroundColor: palette.navBg,
      paddingVertical: 12,
      paddingBottom: 35,
      borderTopWidth: 1,
      borderTopColor: palette.border2,
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 100,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 10,
    },
    navItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 2,
    },
    navLabel: {
      color: isLight ? '#94a3b8' : '#64748b',
      fontSize: 11,
      marginTop: 4,
      fontWeight: '600',
    },
    navLabelActive: {
      color: palette.primary,
      fontWeight: '800',
    },
    dateBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.bg,
      paddingVertical: 0,
      alignSelf: 'center',
      marginTop: 8,
      marginBottom: 0,
    },
    dateText: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '700',
      marginHorizontal: 16,
      paddingVertical: 4,
    },
    headerTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    profileButton: {
      padding: 4,
    },
    // Modals
    modalOverlay: {
      flex: 1,
      backgroundColor: palette.overlay,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      backgroundColor: palette.bg2,
      borderRadius: 16,
      padding: 24,
      width: '90%',
      maxHeight: '90%',
      minHeight: 400,
      borderWidth: 1,
      borderColor: palette.border,
    },
    modalTitle: {
      color: palette.text,
      fontSize: 20,
      fontWeight: '600',
      textAlign: 'center',
      marginBottom: 8,
    },
    modalSubtitle: {
      color: palette.textMuted,
      fontSize: 14,
      textAlign: 'center',
      marginBottom: 20,
    },
    waterInput: {
      backgroundColor: palette.inputBg,
      borderRadius: 8,
      padding: 16,
      color: palette.text,
      fontSize: 16,
      marginBottom: 16,
      textAlign: 'center',
      position: 'relative',
      borderWidth: 1,
      borderColor: palette.border,
    },
    clearButton: {
      position: 'absolute',
      right: 16,
      top: 16,
      zIndex: 1,
    },
    quickButtons: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 24,
    },
    quickButton: {
      backgroundColor: palette.inputBg,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: palette.border,
    },
    quickButtonText: {
      color: palette.primary,
      fontSize: 14,
      fontWeight: '500',
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    modalButton: {
      flex: 1,
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      minHeight: 50,
    },
    inlineButton: {
      flex: 0,
      alignSelf: 'center',
      minWidth: 140,
      paddingVertical: 10,
      paddingHorizontal: 16,
      minHeight: 42,
      marginTop: 10,
    },
    fullWidthButton: {
      flex: 0,
      alignSelf: 'stretch',
      width: '100%',
      paddingVertical: 14,
      minHeight: 50,
      marginTop: 10,
    },
    cancelButton: {
      backgroundColor: palette.inputBg,
      borderWidth: 1,
      borderColor: palette.border,
    },
    confirmButton: {
      backgroundColor: palette.primary,
    },
    compactButton: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      minHeight: 42,
      marginTop: 6,
    },
    cancelButtonText: {
      color: palette.textMuted,
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
      includeFontPadding: false,
    },
    confirmButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
      includeFontPadding: false,
    },
    compactButtonText: {
      fontSize: 15,
    },
    mentalOptionsContainer: {
      maxHeight: 300,
      marginBottom: 20,
    },
    mentalOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginBottom: 8,
      backgroundColor: palette.inputBg,
      borderWidth: 1,
      borderColor: palette.border,
    },
    selectedMentalOption: {
      backgroundColor: isLight ? 'rgba(139, 92, 246, 0.08)' : 'rgba(139, 92, 246, 0.15)',
      borderColor: '#8b5cf6',
      borderWidth: 2,
    },
    mentalOptionText: {
      color: palette.text,
      fontSize: 16,
      marginLeft: 12,
      fontWeight: '500',
    },
    selectedMentalOptionText: {
      color: '#8b5cf6',
      fontWeight: '700',
    },
    currentWaterDisplay: {
      backgroundColor: isLight ? '#f5f3ff' : 'rgba(139, 92, 246, 0.1)',
      padding: 20,
      borderRadius: 20,
      marginBottom: 24,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isLight ? '#ede9fe' : 'rgba(139, 92, 246, 0.2)',
    },
    currentWaterValue: {
      color: palette.primary,
      fontSize: 32,
      fontWeight: '800',
      letterSpacing: -1,
    },
    currentWaterGoal: {
      color: palette.textMuted,
      fontSize: 14,
      fontWeight: '600',
      marginTop: 4,
    },
    waterAmountSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 20,
      marginBottom: 32,
    },
    waterCircleButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: palette.inputBg,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    waterAmountText: {
      color: palette.text,
      fontSize: 28,
      fontWeight: '700',
      minWidth: 100,
      textAlign: 'center',
    },
    waterPresetsContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 12,
      marginBottom: 32,
    },
    waterPresetChip: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: palette.inputBg,
      borderWidth: 1,
      borderColor: palette.border,
      alignItems: 'center',
    },
    waterPresetText: {
      color: palette.text,
      fontSize: 14,
      fontWeight: '600',
    },
    waterPresetAmount: {
      color: palette.textMuted,
      fontSize: 12,
      marginTop: 2,
    },
    waterActionButtons: {
      flexDirection: 'row',
      gap: 12,
    },
    waterActionButton: {
      flex: 1,
      height: 56,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    },
    waterAddButton: {
      backgroundColor: palette.primary,
    },
    waterSubtractButton: {
      backgroundColor: isLight ? '#fef2f2' : '#2d1a1a',
      borderWidth: 1,
      borderColor: isLight ? '#fee2e2' : '#451a1a',
    },
    waterAddButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '700',
    },
    waterSubtractButtonText: {
      color: '#ef4444',
      fontSize: 16,
      fontWeight: '700',
    },
    categoryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginTop: 24,
      marginBottom: 24,
      gap: 16,
      paddingHorizontal: 4,
    },
    categoryCard: {
      width: '47%',
      backgroundColor: palette.bg2,
      borderRadius: 20,
      alignItems: 'center',
      paddingVertical: 32,
      paddingHorizontal: 16,
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      borderWidth: 1,
      borderColor: palette.border,
    },
    categoryTitle: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '700',
      marginTop: 12,
      textAlign: 'center',
    },
    categorySummary: {
      color: palette.textMuted,
      fontSize: 12,
      marginTop: 6,
      textAlign: 'center',
      lineHeight: 16,
    },
    sheetOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.3)',
      justifyContent: 'flex-end',
    },
    sheetOverlayTouch: {
      flex: 1,
    },
    bottomSheet: {
      backgroundColor: palette.bg,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 20,
      height: 500,
      elevation: 10,
    },
    sheetHandle: {
      width: 48,
      height: 6,
      borderRadius: 3,
      backgroundColor: isLight ? '#e5e7eb' : '#333',
      alignSelf: 'center',
      marginBottom: 16,
    },
    sheetContent: {
      flex: 1,
    },
    sheetScrollView: {
      flex: 1,
      paddingHorizontal: 4,
    },
    sheetTitle: {
      color: palette.text,
      fontSize: 20,
      fontWeight: '700',
      marginBottom: 16,
      textAlign: 'center',
    },
    sheetCards: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      justifyContent: 'space-between',
      paddingBottom: 20,
    },
    inputGroup: {
      marginBottom: 16,
    },
    inputLabel: {
      color: palette.textMuted,
      fontSize: 14,
      marginBottom: 8,
    },
    profileInput: {
      backgroundColor: palette.inputBg,
      borderRadius: 8,
      padding: 16,
      color: palette.text,
      fontSize: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
    profileInfo: {
      backgroundColor: palette.inputBg,
      borderRadius: 8,
      padding: 16,
      marginTop: 8,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.border,
    },
    profileInfoText: {
      color: palette.textMuted,
      fontSize: 14,
    },
    profileSection: {
      marginTop: 0,
    },
    profileCard: {
      backgroundColor: palette.bg2,
      borderRadius: 16,
      padding: 20,
      marginTop: 12,
      borderWidth: 1,
      borderColor: palette.border,
    },
    profileCardContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    profileCardText: {
      flex: 1,
      marginLeft: 16,
    },
    profileCardTitle: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '600',
    },
    profileCardSubtitle: {
      color: palette.textMuted,
      fontSize: 14,
      marginTop: 2,
    },
    physicalStatsGrid: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 12,
    },
    physicalStatCard: {
      flex: 1,
      backgroundColor: palette.bg2,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
    physicalStatContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    physicalStatText: {
      flex: 1,
      marginLeft: 12,
    },
    physicalStatTitle: {
      color: palette.textMuted,
      fontSize: 14,
      marginBottom: 2,
    },
    physicalStatValue: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '600',
    },
    editButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: palette.inputBg,
      borderWidth: 1,
      borderColor: palette.border,
    },
    goalsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginTop: 12,
      gap: 12,
    },
    goalCard: {
      width: '47%',
      backgroundColor: palette.bg2,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
    goalCardContent: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    goalCardText: {
      flex: 1,
      marginLeft: 12,
    },
    goalCardTitle: {
      color: palette.textMuted,
      fontSize: 14,
      marginBottom: 2,
    },
    goalCardValue: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '600',
    },
    activityOptionText: {
      marginLeft: 12,
    },
    activityOptionDescription: {
      color: palette.textMuted,
      fontSize: 12,
      marginTop: 2,
    },
    modalHeader: {
      alignItems: 'center',
      marginBottom: 16,
    },
    currentWeightSection: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.inputBg,
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
    currentWeightText: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 10,
    },
    optionsSection: {
      marginBottom: 16,
    },
    sectionLabel: {
      color: palette.textMuted,
      fontSize: 14,
      marginBottom: 8,
    },
    goalOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginBottom: 8,
      backgroundColor: palette.inputBg,
      borderWidth: 1,
      borderColor: palette.border,
    },
    selectedGoalOption: {
      backgroundColor: isLight ? 'rgba(139, 92, 246, 0.08)' : 'rgba(139, 92, 246, 0.15)',
      borderColor: '#8b5cf6',
      borderWidth: 2,
    },
    goalOptionIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isLight ? '#f5f3ff' : 'rgba(139, 92, 246, 0.1)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    goalOptionContent: {
      flex: 1,
    },
    goalOptionTitle: {
      color: palette.text,
      fontSize: 16,
      fontWeight: '500',
    },
    goalOptionDescription: {
      color: palette.textMuted,
      fontSize: 12,
      marginTop: 2,
    },
    selectedGoalOptionText: {
      color: '#8b5cf6',
      fontWeight: '700',
    },
    targetSection: {
      marginTop: 16,
    },
    targetInput: {
      backgroundColor: palette.inputBg,
      borderRadius: 8,
      padding: 16,
      color: palette.text,
      fontSize: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: palette.border,
    },
  });

  return { ...styles, colors: palette };
}