import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // Meals-specific modal styles
  mealsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end', // Anchor to bottom
    alignItems: 'center',
  },
  mealsModalContent: {
    backgroundColor: '#1a1a1a',
    borderRadius: 20,
    padding: 24,
    width: '95%',
    maxHeight: '95%',
    minHeight: 500,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  mealsModalTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 16,
  },
  mealsModalSubtitle: {
    color: '#aaa',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 24,
  },
  mealsWaterInput: {
    backgroundColor: '#2a2a2a',
    borderRadius: 12,
    padding: 16,
    color: '#fff',
    fontSize: 18,
    marginBottom: 16,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: '#444',
  },
  mealsClearButton: {
    position: 'absolute',
    right: 16,
    top: 16,
    zIndex: 1,
  },
  mealsQuickButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 24,
    flexWrap: 'wrap',
    gap: 8,
  },
  mealsQuickButton: {
    backgroundColor: '#2a2a2a',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#444',
  },
  mealsQuickButtonText: {
    color: '#a78bfa',
    fontSize: 16,
    fontWeight: '600',
  },
  mealsModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 16,
  },
  mealsModalButton: {
    flex: 1,
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    minHeight: 56,
  },
  mealsCancelButton: {
    backgroundColor: '#2a2a2a',
    borderWidth: 1,
    borderColor: '#444',
  },
  mealsConfirmButton: {
    backgroundColor: '#8b5cf6',
    borderWidth: 1,
    borderColor: '#7c3aed',
  },
  mealsCancelButtonText: {
    color: '#aaa',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    includeFontPadding: false,
  },
  mealsConfirmButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    includeFontPadding: false,
  },
  // Quantity input styles
  quantitySection: {
    marginBottom: 20,
  },
  quantityLabel: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
  },
  quantityInput: {
    backgroundColor: '#2a2a2a',
    borderRadius: 12,
    padding: 16,
    color: '#fff',
    fontSize: 18,
    marginBottom: 16,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: '#444',
  },
  quantityButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    flexWrap: 'wrap',
    gap: 8,
  },
  quantityButton: {
    backgroundColor: '#2a2a2a',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#444',
    minWidth: 80,
    alignItems: 'center',
  },
  quantityButtonText: {
    color: '#a78bfa',
    fontSize: 16,
    fontWeight: '600',
  },
  // Food info styles
  foodInfoSection: {
    backgroundColor: '#2a2a2a',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
  },
  foodName: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 8,
  },
  foodBrand: {
    color: '#888',
    fontSize: 16,
    marginBottom: 16,
  },
  // Macros display
  macrosGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  macroItem: {
    alignItems: 'center',
    flex: 1,
  },
  macroValue: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
  macroLabel: {
    color: '#888',
    fontSize: 12,
    marginTop: 4,
  },
  // Serving selection
  servingSection: {
    marginBottom: 20,
  },
  servingGrid: {
    gap: 8,
  },
  servingButton: {
    backgroundColor: '#2a2a2a',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#444',
  },
  servingButtonSelected: {
    backgroundColor: '#8b5cf6',
    borderColor: '#8b5cf6',
  },
  servingButtonText: {
    color: '#aaa',
    fontSize: 16,
    fontWeight: '500',
  },
  servingButtonTextSelected: {
    color: '#fff',
    fontWeight: '600',
  },
  servingCalories: {
    color: '#666',
    fontSize: 14,
    marginTop: 4,
  },
  servingCaloriesSelected: {
    color: '#ccc',
  },
  // Meal selection
  mealSection: {
    marginBottom: 20,
  },
  mealGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  mealButton: {
    backgroundColor: '#2a2a2a',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#444',
  },
  mealButtonSelected: {
    backgroundColor: '#8b5cf6',
    borderColor: '#8b5cf6',
  },
  mealButtonText: {
    color: '#aaa',
    fontSize: 16,
    fontWeight: '500',
  },
  mealButtonTextSelected: {
    color: '#fff',
    fontWeight: '600',
  },
  // --- PREMIUM UI ADDITIONS ---
  premiumModalContent: {
    backgroundColor: '#161616',
    borderTopLeftRadius: 32, // More rounded top
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    width: '100%', // Full width
    maxHeight: '85%', // Slightly less height
    minHeight: 500,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    overflow: 'hidden',
  },
  premiumModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
    backgroundColor: '#1a1a1a',
  },
  premiumModalTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  closeButtonCircle: {
    backgroundColor: '#333',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  foodIdentityCard: {
    paddingHorizontal: 24,
    marginTop: 12,
    marginBottom: 20,
  },
  foodNameLarge: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
    marginBottom: 10,
  },
  brandBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#8b5cf620',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#8b5cf640',
  },
  foodBrandText: {
    color: '#a78bfa',
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  premiumMacroGrid: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    backgroundColor: '#1a1a1a',
    paddingVertical: 18,
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#262626',
  },
  premiumMacroCard: {
    alignItems: 'center',
    flex: 1,
  },
  premiumMacroIcon: {
    marginBottom: 6,
  },
  premiumMacroValue: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  premiumMacroLabel: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 2,
  },
  premiumSectionDivider: {
    height: 1,
    backgroundColor: '#333',
    marginHorizontal: 24,
    marginVertical: 10,
  },
  premiumSection: {
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  premiumSectionLabel: {
    color: '#666',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 16,
  },
  modeSelector: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 24,
  },
  modeTab: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#222',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
    gap: 8,
  },
  modeTabActive: {
    backgroundColor: '#8b5cf6',
    borderColor: '#7c3aed',
  },
  modeTabText: {
    color: '#888',
    fontSize: 14,
    fontWeight: '600',
  },
  modeTabTextActive: {
    color: '#fff',
  },
  quantityAdjusterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#111', // Dark bg
    borderRadius: 24,
    padding: 12,
    borderWidth: 2,
    borderColor: '#333', // Thicker border
    marginTop: 12,
    marginBottom: 12,
    minHeight: 70, // Force height
  },
  adjustButton: {
    backgroundColor: '#8b5cf6',
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#8b5cf6',
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  quantityInputWrapper: {
    alignItems: 'center',
    flex: 1,
  },
  premiumQuantityInput: {
    color: '#fff',
    fontSize: 34,
    fontWeight: '900',
    textAlign: 'center',
    width: '100%',
    paddingVertical: 4,
    letterSpacing: -1,
    borderBottomWidth: 2,
    borderBottomColor: '#333', // Subtle underline to show it is editable
    backgroundColor: '#1a1a1a', // Slight contrast
    borderRadius: 8,
  },
  unitSubtext: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '700',
    marginTop: -2,
    textTransform: 'uppercase',
  },
  premiumMealGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  premiumMealBtn: {
    backgroundColor: '#222',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
    minWidth: '30%',
    alignItems: 'center',
  },
  premiumMealBtnActive: {
    backgroundColor: '#8b5cf6',
    borderColor: '#a78bfa',
  },
  premiumMealBtnText: {
    color: '#888',
    fontSize: 14,
    fontWeight: '600',
  },
  premiumMealBtnTextActive: {
    color: '#fff',
  },
  premiumFooter: {
    flexDirection: 'row',
    padding: 24,
    backgroundColor: '#1a1a1a',
    gap: 16,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  actionBtn: {
    flex: 1,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  primaryActionBtn: {
    backgroundColor: '#8b5cf6',
    elevation: 8,
    shadowColor: '#8b5cf6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
  },
  secondaryActionBtn: {
    backgroundColor: '#252525',
    borderWidth: 1,
    borderColor: '#333',
  },
  primaryActionText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryActionText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});

export default styles; 